import { CompanyScale } from "@/types/enum";
import { Job } from "src/types/interface";

export const jobs: Job[] = [
    {
        id: 0,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
    {
        id: 1,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
    {
        id: 2,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
    {
        id: 3,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
    {
        id: 4,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
    {
        id: 5,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
    {
        id: 6,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
    {
        id: 7,
        name: "Unreal 引擎专家",
        company: {
            id: 1,
            name: "米哈游科技（上海）有限公司",
            logo: "logo1",
            industry: "industry1",
            description: "description1",
            address: "address1",
            tel: "tel1",
            scale: CompanyScale.LV500,
        },
        salary: "30k-50k",
        city: "beijing",
        address: "广州",
        description: "description1",
        tags: ["上海市", "经验不限", "学历不限"],
        comments: [
            {
                id: 1,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
            {
                id: 2,
                author: "金色传说",
                content: "这个职位很不错",
                addTime: "2020-01-01",
            },
        ],
    },
];
